name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
        # add this step
    - name: Set up GOPATH
      run: |
        echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
        echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"

    - name: Get Requirements
      run: |
        sudo apt-get -y install restic
        sudo apt-get install findutils

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2  
      with:
        path: src/github.com/azak-azkaran/agent
      
    - name: Make Coverage Reports
      run: make coverage
      working-directory: src/github.com/azak-azkaran/agent
      
    - name: Update SonarProject Version
      run: echo "sonar.projectVersion=`git describe --tags --abbrev=0`" >> sonar-project.properties
      working-directory: src/github.com/azak-azkaran/agent
      
    - name: SonarCloud Scan
      # You may pin to the exact commit or the version.
      # uses: SonarSource/sonarcloud-github-action@f4c6e4d91ea9785ec823eaeed459042606123402
      uses: SonarSource/sonarcloud-github-action@v1.4
      with:
        projectBaseDir: src/github.com/azak-azkaran/agent
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Install Coveralls
      env:
        GO111MODULE: off
      run: go get github.com/mattn/goveralls

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=cover.out -service="github"
      working-directory: src/github.com/azak-azkaran/agent
